<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>HeadsetStats</AssemblyName>
    <RootNamespace>HeadsetStats.Tray</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeadsetStats.Core\HeadsetStats.Core.csproj" />
  </ItemGroup>

</Project>
